layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: markusmo3
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: markusmo3
  twitter: markusmo3
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Docker
    web_url: https://www.docker.com
    image_url: https://www.docker.com/sites/default/files/d8/2019-07/vertical-logo-monochromatic.png

  - name: Software Architecture

  - name: Kotlin
    web_url: https://kotlinlang.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/7/74/Kotlin-logo.svg
